### ISSUE TITLE
Footnotes not displaying if names contain hyphens

### ISSUE THREAD

**Issue by paulhibbitts** [sy-records/docsify-footnotes#1]
Thank you so much for putting this super helpful plugin together! In the open education and publishing space support for footnotes is really critical🙂

A colleague of mine recently shared a Markdown doc with footnotes where some footnote names contained hyphens, and the current version of this plugin would not display these as expected. With the help of ChatGPT, I was able to modify the RegEx used so that hyphens were supported in footnote names.

This change was to replace `[A-Za-z0-9]` with `[A-Za-z0-9\-]` to allow hyphens within the footnote name. Please feel free to incorporate this update into your plugin if you like to then support hyphens as well. The Markdown file in question is https://github.com/OleVik/Digital-Publishing-System-Framework/blob/main/README.md and with this change Docsify-This now renders the footnotes correctly https://docsify-this.net/?basePath=https://raw.githubusercontent.com/OleVik/Digital-Publishing-System-Framework/main&homepage=README.md&sidebar=true

Thanks again, and also thanks for your continued work as a Docsify Maintainer!
Paul

**Comment by sy-records** [comment]
I made the changes and released v1.0.2. 

Thanks for the sponsor. 🎉
